### PR TITLE
Support read-only attributes.

### LINKED ISSUE #347: LDAP-312: more flexibility for attribute mapping
[Brett Maxfield](https://jira.spring.io/secure/ViewProfile.jspa?name=maxfieb) (Migrated from [LDAP-312](https://jira.spring.io/browse/LDAP-312?redirect=false)) said:

There seems be some things missing in the Spring-LDAP ODM annotations. 
1. I'd like to mark an @Attribute as read-only, so it will populate the bean from LDAP for reference, but not persist it back to ldap. I'd suggest adding an attribute read-only to @Attribute, defaulting to false, for the usual case.
2. The default attributes of \* misses all the operational attributes, some of which are very useful, and transfers more data than is required, slowing down the ldap query with attributes which will never be used.

An example of this; it would be very useful, for literally read only, such as entryUUID, etag, etc., which you cannot use if you wish to persist only some fields back to ldap, as the bean fails to persist to ldap with an exception when you save the bean. But also would be useful for general fields which you want to structurally prevent the user from ever updating.

You can get around this by not annotating read-only fields, and then manually populating the read only fields with a separate call. Very messy and kills the query speed.

Also on a related topic, query() could have a default list of attributes, which you have already annotated in your classes, something like :

public static String[] getBeanAttributes(Class<?> beanClass) {
    ArrayList<String> attrsObj = new ArrayList<>();
    for (Field field : beanClass.getDeclaredFields()) {
        if (field.isAnnotationPresent(Attribute.class)) {
            Attribute attr = field.getAnnotation(Attribute.class);
            attrsObj.add(attr.name());
        }
    }
    String[] attrs = attrsObj.toArray(new String[attrsObj.size()]);
    return attrs;
}

Above just returns a simple String[] of your declared attributes, to pass to query.attributes() - now i realize that as a static member, query() is built before the bean class is known, but at least there could be a helper function like the above, or a method signature for query attributes() that took a bean Class signature as an argument.

### PR DESCRIPTION
**Pull request by kwin**
Also always explicitly request only the necessary attributes (makes
operational attributes work).

This closes #347

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kwin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=425)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=425) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kwin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=425)!

**Comment by kwin** [comment]
This PR includes the work from Brett Maxfield from https://jira.spring.io/browse/LDAP-312 and additionally makes sure that only the relevant attributes are always requested (implicitly supports operational attributes that way).

**Comment by kwin** [comment]
Some tests are failing:

1. One in `spring-ldap-core` within `LdapTemplateLookupTest` where mocking was no properly done on the given `Name` (I just ignored that one)
1. Several ones in `spring-ldap-odm` which probably all have to do with the fact that there is no annotation set on https://github.com/spring-projects/spring-ldap/blame/master/odm/src/test/java/org/springframework/ldap/odm/test/Person.java#L69. 

Maybe someone can give a hint on how to fix those?

**Comment by rwinch** [comment]
Thanks for the PR @kwin! In order to merge this, we need tests to be added. Is this something you can do? Also we cannot disable / modify existing tests unless it is a bug.

**Comment by kwin** [comment]
Ok, I fixed the one failing test and also extended the unit test to cover the additional functionality. All tests were only extended (but not actually modified in what they test). Hopefully this is enough on the unit test side.

Only ITs is something I cannot easily provide. Could someone else add a test which mainly checks that readonly attributes are not written back to LDAP and that operational attributes are now retrieved with ODM?

**Comment by kwin** [comment]
Is anything missing from this PR to merge it?

**Pull request merged**
