### PR TITLE
Fix for #31

### PR DESCRIPTION
**Pull request by bhuism**

### CODE REVIEW

**Comment by bhuism** [comment]
@rwinch, would it be possible to merge this PR? I have signed de 'Individual Contributor Agreement'

**Comment by rwinch** [comment]
@bhuism Thanks for the PR!

Unfortuantely, we cannot merge non passive changes. Since this modifies a public interface we cannot merge the pull request. If you can come up with a passive way of resolving this issue we can look into getting this merged.

**Comment by bhuism** [comment]
@rwinch thanks! the interface is not modified, the behavior is modified.

Is it allowed to change the the behavior of a method? 

If not how should https://github.com/spring-projects/spring-ldap/issues/31 be fixed in your opinion?

**Comment by rwinch** [comment]
@bhuism Thanks for the fast response. 

Perhaps I am missing something due to only looking in the diff, but it appears that [a new method was added](https://github.com/spring-projects/spring-ldap/pull/35/files#diff-1c45302168ad67fdc93e96d96098b1afR1791) to `LdapOperations`. This constitutes as a change because anyone implementing the interface must now add a new method.

**Comment by bhuism** [comment]
Ah, I got ya, I'll try to make a PR another way, thanks!

**Comment by bhuism** [comment]
@rwinch would it be ok to add the new method to `LdapOperations` in 2.1.0? in stead of 2.0.x? I can't fix I cleanly without the interface change.

**Comment by rwinch** [comment]
@bhuism We cannot add a method until 3.x since we follow [APR Versioning](https://apr.apache.org/versioning.html)

**Pull request closed without merging**
