### PR TITLE
Add unboundid embedded ldap server

### PR DESCRIPTION
**Pull request by eddumelendez**
Previous to this commit, the only provider for embedded ldap server was
apacheds. Now, unboundid can be used as a option for testing purpose.

See gh-386

### CODE REVIEW

**Comment by rwinch** [comment]
@eddumelendez Thanks for the PR! Like using ApacheDS, we are going to need to get this added to Spring IO in order to merge this. Can you create a ticket at https://github.com/spring-io/platform/issues and mention me on it?

**Comment by eddumelendez** [comment]
@rwinch Sure. Done.

**Comment by eddumelendez** [comment]
@rwinch since `spring-io` managed `unboundid:ldap-sdk` as a dependency and `spring-ldap` is running under `spring-io:2.1.0-SNAPSHOT`. This PR will be in a major release, right?

**Comment by rwinch** [comment]
@eddumelendez Yes. I plan to put it in the next release. Thanks for reminding me to update this issue

**Comment by pivotal-issuemaster** [comment]
@eddumelendez Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by eddumelendez** [comment]
@rwinch signed!

**Comment by pivotal-issuemaster** [comment]
@eddumelendez Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=399)!

**Comment by rwinch** [comment]
Thanks for the PR! This is merged via 594c3616581a9ae3b10b5c6a314821a194a8c7c6 and I gave it some Polish in 1a5bead76d825bfd968e76b5563269a30d05f2bd

**Pull request closed without merging**
