### PR TITLE
Implemented logging for LDAP searches performed by LdapTemplate

### LINKED ISSUE #345: LDAP-310: Log LDAP queries generated by spring-ldap
[Jose Martinez](https://jira.spring.io/secure/ViewProfile.jspa?name=jmartinez@knoa.com) (Migrated from [LDAP-310](https://jira.spring.io/browse/LDAP-310?redirect=false)) said:

I would be useful for the debugging purposes to have log the final query string sent to the server as well as the parameters. Something we can copy-paste into the LDAP server and see how it runs. Similar to the way JdbcTemplate shows the queries and parameters executing a query. 

I'm creating this Jira as per the following StackOverflow post: https://stackoverflow.com/questions/24061834/how-to-see-the-query-generated-by-spring-ldaptemplate.

### PR DESCRIPTION
**Pull request by Haarolean**
Hi,

I've implemented some logging for LDAP searches performed within `LdapTemplate`. Resolves #345.
I believe this will help and greatly improve the experience using spring-ldap, as the issues people (and I personally) encounter usually are hard to debug or investigate.

1) I've extracted some common parts to reduce/prevent code duplications and added logging there;
2) I've spotted some straight-to-fix warnings and some anonymous classes with lambdas, so I took the liberty. These changes can be viewed independently within one of the two commits in this PR. Let me know if these changes are unwanted, and I'll revert.
3) The test run is successful: `BUILD SUCCESSFUL in 1m 44s; 67 actionable tasks: 57 executed, 10 up-to-date`

Cheers

### CODE REVIEW

**Comment by Haarolean** [comment]
@jzheaux hey, sorry for the ping. Is there anything else I could do here to add some traction to the PR? 
I'd even apply for a position at VMware to help out with maintenance stuff but they're not hiring atm :-))

**Comment by jzheaux** [comment]
@Haarolean, sorry for the delay. I'm taking a look this week.

**Comment by jzheaux** [comment]
Thanks, @Haarolean! This is now merged into `main`.

**Comment by Haarolean** [comment]
@jzheaux thank you!

**Comment by ranma2913** [comment]
Thanks for adding this. It's going to help out my project right away since I'm working on running native queries.

**Pull request merged**
