### PR TITLE
Fix for issue #492: Support UTF8 characters in attributes values for …

### PR DESCRIPTION
**Pull request by naorbar**
…LDIF's DefaultAttributeValidationPolicy in order to comply with RFC2849

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@naorbar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=493)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=493) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@naorbar Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=493)!

**Comment by rwinch** [comment]
@naorbar Thanks for the PR! Unfortunately one of the tests is now [failing in Travis](https://travis-ci.org/spring-projects/spring-ldap/builds/427643078)

```

org.springframework.ldap.ldif.DefaultAttributeValidationPolicyTest > parseAttribute[28] FAILED
    java.lang.AssertionError at DefaultAttributeValidationPolicyTest.java:176
```

Can you push a fix to the code?

**Comment by naorbar** [comment]
Rob,
I changed the encoding on my IDE to UTF8 to comply with Travis's encoding, and saved again the source file.
The build passed.
Thanks,
Naor

**Comment by rwinch** [comment]
@naorbar Thanks for fixing the build! This is now merged into master

**Comment by naorbar** [comment]
With pleasure. Let me know if I can help in the future...

**Pull request merged**
