### PR TITLE
fix NamingEnumeration not closed

### PR DESCRIPTION
**Pull request by antoine777**
see Issue [#489](https://github.com/spring-projects/spring-ldap/issues/489)

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! Waiting for the travis build to be fixed. See https://github.com/spring-projects/spring-ldap/issues/489#issuecomment-606268597

**Comment by michael-o** [comment]
Any chance to get this merged?

**Comment by michael-o** [comment]
Ping! @rwinch

**Comment by jzheaux** [comment]
Closing in favor of https://github.com/spring-projects/spring-ldap/pull/609

**Pull request closed without merging**
